<?php

declare(strict_types=1);

namespace Yard\Brave\Boost\Install;

use RuntimeException;
use Yard\Brave\Boost\Contracts\Agent;
use Yard\Brave\Boost\Support\Paths;

/**
 * Writes the composed guideline block into an agent's file, wrapped in marker
 * tags. Any content outside the tags (the developer's own notes) is preserved;
 * an existing block is replaced in place.
 */
class GuidelineWriter
{
	protected const OPEN = '<brave-boost-guidelines>';

	protected const CLOSE = '</brave-boost-guidelines>';

	protected const HINT = '<!-- Generated by brave-boost. Do not edit inside. -->';

	protected const HEADER = "# AI guidelines\n\nProject-specific notes can live outside the brave-boost markers.";

	public function __construct(protected Agent $agent)
	{
	}

	public function write(string $guidelines): void
	{
		$path = Paths::project($this->agent->guidelinesPath());

		$this->ensureDirectory(dirname($path));

		$block = self::OPEN."\n".self::HINT."\n\n".trim($guidelines)."\n".self::CLOSE;

		$existing = is_file($path) ? (string) file_get_contents($path) : '';

		$contents = $this->hasBlock($existing)
			? $this->replaceBlock($existing, $block)
			: $this->appendBlock($existing, $block);

		if (file_put_contents($path, $contents) === false) {
			throw new RuntimeException("Failed to write guidelines to {$path}");
		}
	}

	protected function hasBlock(string $contents): bool
	{
		return str_contains($contents, self::OPEN) && str_contains($contents, self::CLOSE);
	}

	protected function replaceBlock(string $contents, string $block): string
	{
		$pattern = '/'.preg_quote(self::OPEN, '/').'.*?'.preg_quote(self::CLOSE, '/').'/s';

		return (string) preg_replace($pattern, $this->escapeReplacement($block), $contents, 1);
	}

	protected function appendBlock(string $existing, string $block): string
	{
		if (trim($existing) === '') {
			$prefix = $this->agent->frontmatter() ? "---\nalwaysApply: true\n---\n\n" : '';

			return $prefix.self::HEADER."\n\n".$block."\n";
		}

		return rtrim($existing)."\n\n===\n\n".$block."\n";
	}

	protected function ensureDirectory(string $dir): void
	{
		if (! is_dir($dir) && ! mkdir($dir, 0755, true) && ! is_dir($dir)) {
			throw new RuntimeException("Failed to create directory {$dir}");
		}
	}

	protected function escapeReplacement(string $value): string
	{
		// preg_replace treats $ and \ specially in the replacement string.
		return str_replace(['\\', '$'], ['\\\\', '\\$'], $value);
	}
}
